server:
  port: 5233
spring:
  datasource:
    url: jdbc:mysql://182.92.229.1:3306/remind?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 182.92.229.1
    port: 6379
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    connect-timeout: 30000
    password:
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xiaoyc.remind.entity
