server:
  port: 5233
spring:
  datasource:
    url: jdbc:mysql://182.92.229.1:3306/remind?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xiaoyc.remind.entity
